quarkus.log.console.json=false

#Datasource Configuration [Test]
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.max-size=13
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2-console
quarkus.hibernate-orm.sql-load-script=import.sql

# Não utiliza CredentialProvider
quarkus.datasource.credentials-provider=
quarkus.datasource.credentials-provider-name=