##################################################################################################################
quarkus.log.level=INFO

##################################################################################################################
# Config JPA - Ignore Database & Hibernate DDL Auto
quarkus.hibernate-orm.schema-management.strategy=update

##################################################################################################################
# -- Database MySQL
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/envlocaldb
quarkus.datasource.username=dbmysql
quarkus.datasource.password=${DB_PASSWORD_KEY:dbmysql123}
quarkus.hibernate-orm.log.sql=true

# -----> default connection pool
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=30S

##################################################################################################################