##################################################################################################################
quarkus.log.level=INFO

##################################################################################################################
# -- Database H2 Memory Configs:
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:mydblocal;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.log.sql=true

# -----> default connection pool
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=30S

# Config JPA - Ignore Database & Hibernate DDL Auto
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

##################################################################################################################
# -- Database MongoDB
#quarkus.mongodb.connection-string=mongodb://localhost:27017?retryWrites=false
#quarkus.mongodb.database=db_btgpactual?retryWrites=false

quarkus.mongodb.connection-string=mongodb://localhost:27017/db_btgpactual?retryWrites=false
quarkus.mongodb.database=db_btgpactual

# Credenciiais
quarkus.mongodb.credentials.username=admin
quarkus.mongodb.credentials.password=admin123
quarkus.mongodb.credentials.auth-source=admin

# Habilita a criação automática dos índices anotados com @Indexed e @CompositeIndex
quarkus.mongodb.panache.create-indexes=true

# Opção B: Salvar como String/Texto (Recomendado para legibilidade visual nas consultas)
#quarkus.mongodb.uuid-representation=c_sharp_legacy
#quarkus.mongodb.uuid-representation=standard

##################################################################################################################
# RabbitMQ Configs
# ==========================================
# 1. RabbitMQ configurações de conexão
# ==========================================
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# =========================================================
# 2. Incoming Channel Configuration (Consumer)
# ========================================================
# Channel name used inside your Java code - For an INCOMING (consumer) channel:
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.connector=smallrye-rabbitmq
# RabbitMQ Queue to consume from
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.name=btg-pactual-orderbtgpactual-created
# Explicitly enable auto-declaration
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.declare=true
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.durable=true

mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.exchange.name=orders-exchange
#mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.exchange.type=topic
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.exchange.type=direct
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.routing-keys=order-created-key
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.auto-bind=true

#
#mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.failure-strategy=requeue
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.failure-strategy=reject
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.dead-letter-exchange=DLX
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.dead-letter-routing-key=btg-pactual-order-dlq

#mp.messaging.incoming.btg-pactual-orderbtgpactual-createdin.auto-bind-dlq=true
#mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.auto-bind-dlq=false

# DLQ
#mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.dead-letter-exchange=DLX
#mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.failure-strategy=requeue

mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.content-type-override=text/plain

# Sets x-max-priority on queue creation
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.arguments.x-max-priority=10

# Configures a Quorum Queue
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.arguments.x-queue-type=quorum

# Configures Overflow Behavior
mp.messaging.incoming.btg-pactual-orderbtgpactual-created-in.queue.arguments.x-overflow=reject-publish

# ==========================================================
# 3. Outgoing Channel Configuration (Producer/Publish)
# ==========================================================
# Channel name used inside your Java code
#mp.messaging.outgoing.orders-out.connector=smallrye-rabbitmq
## For an OUTGOING (producer) channel:
#mp.messaging.outgoing.btg-pactual-orderbtgpactual-created.connector=smallrye-rabbitmq
## Target Exchange
#mp.messaging.outgoing.orders-out.exchange.name=orders-exchange
## Routing Key
#mp.messaging.outgoing.orders-out.default-routing-key=orders.new