# quarkus.profile=itau
quarkus.profile=h2db

##################################################################################################################
#general
quarkus.http.port=8095

##################################################################################################################

quarkus.application.name=API-QUARKUS-GENERAL
quarkus.log.console.json.additional-field."microservice".value=apiquarkusgeneral
quarkus.log.console.json.additional-field."microservice".type=string
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.headers=*
quarkus.http.read-timeout=30S

##################################################################################################################
##### #### ### Default configuration CredentialProvide r# ## ### #####
apiquarkusgeneral.application.log-complete=true
apiquarkusgeneral.application.flag-type-service-consumer=1

##################################################################################################################
# URLS Externas
uol.herogroup.marvel-or-dc-comics.service.url=https://raw.githubusercontent.com/uolhost
