##################################################################################################################
quarkus.log.level=INFO

##################################################################################################################
# Config JPA - Ignore Database & Hibernate DDL Auto
#quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

##################################################################################################################
# -- Database H2 Memory
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:mydblocal
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.log.sql=true
#quarkus.h2.console.enabled=true
#quarkus.h2.console.path=/h2-console

# -----> default connection pool
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=30S